name: crypto_coins_list
description: A new Flutter project Crypto app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  dio: ^5.1.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  intl: ^0.18.0
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0
  auto_route: ^6.3.0
  firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/preview/
    - assets/svg/

  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         style: normal
  #         weight: 700
