name: crypto_coins_list
description: A new Flutter project Crypto app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  dio: ^5.9.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  talker_flutter: ^4.9.3
  talker_dio_logger: ^4.9.3
  talker_bloc_logger: ^4.9.3
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^6.3.0
  firebase_core: ^4.0.0
  url_launcher: ^6.1.7
  share_plus: ^11.0.0
  group_button: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^6.2.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/preview/
    - assets/svg/

  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         style: normal
  #         weight: 700
