// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9lWcKo_XI_j3YknFAjHzg7PZTp0EOPU',
    appId: '1:738890747389:web:daf093d39618d57456dd94',
    messagingSenderId: '738890747389',
    projectId: 'crypto-list-app-exslym',
    authDomain: 'crypto-list-app-exslym.firebaseapp.com',
    storageBucket: 'crypto-list-app-exslym.appspot.com',
    measurementId: 'G-ZT48TTSX2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-MvGb9kKCWFDmkgAxtkAjFcYRyzNRSk',
    appId: '1:738890747389:android:a648e22a0a24c30656dd94',
    messagingSenderId: '738890747389',
    projectId: 'crypto-list-app-exslym',
    storageBucket: 'crypto-list-app-exslym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4BQyVYYEXyCIJSRmQiJvItJ5AEMsvceU',
    appId: '1:738890747389:ios:b19efa52be0dacf856dd94',
    messagingSenderId: '738890747389',
    projectId: 'crypto-list-app-exslym',
    storageBucket: 'crypto-list-app-exslym.appspot.com',
    iosClientId:
        '738890747389-27ckfo36gmoiu2m97ircpkn39s4vtv4q.apps.googleusercontent.com',
    iosBundleId: 'com.exslym.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4BQyVYYEXyCIJSRmQiJvItJ5AEMsvceU',
    appId: '1:738890747389:ios:b19efa52be0dacf856dd94',
    messagingSenderId: '738890747389',
    projectId: 'crypto-list-app-exslym',
    storageBucket: 'crypto-list-app-exslym.appspot.com',
    iosClientId:
        '738890747389-27ckfo36gmoiu2m97ircpkn39s4vtv4q.apps.googleusercontent.com',
    iosBundleId: 'com.exslym.cryptoCoinsList',
  );
}
